-- MySQL Script generated by MySQL Workbench
-- Sáb 01 Jul 2017 13:52:07 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trabalho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trabalho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalho` DEFAULT CHARACTER SET latin1 ;
USE `trabalho` ;

-- -----------------------------------------------------
-- Table `trabalho`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `trabalho`.`topicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`topicos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `id_usuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `trabalho`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `trabalho`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho`.`comentarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(255) NULL DEFAULT NULL,
  `id_Usuario` INT(11) NULL DEFAULT NULL,
  `id_topico` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_usuario_idx` (`id_Usuario` ASC),
  INDEX `fk_id_topico_idx` (`id_topico` ASC),
  CONSTRAINT `fk_id_topico`
    FOREIGN KEY (`id_topico`)
    REFERENCES `trabalho`.`topicos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_usuario_comentario`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `trabalho`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = latin1;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
